name: Static Analysis
on:
  pull_request:
    branches: [master]
env:
  CMAKE_FLAGS: -DCLOVE_ENABLE_ASSERTIONS=ON -DCLOVE_ENABLE_DEBUG_DEFINITION=ON -DCLOVE_ENABLE_PROFILING=OFF -DCLOVE_LOG_LEVEL=2 -DCLOVE_USE_SAFE_CAST=ON -DGAR_BUILD_TESTS=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
  BUILD_TYPE: Release
jobs:
  cpp_check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/agarlicmonkey/clove/linux_analysis:2.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
        #Suppress syntax errors as these are causing false positives
      - run: cppcheck -iclove/components/core/graphics/external/shaderc -iclove/external/stb ./ --suppress=syntaxError --error-exitcode=1
  #macOS
  clang-tidy-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup environment
        run: |
          mkdir build
          brew update
          brew install conan
          brew install llvm
          ln -s "/usr/local/opt/llvm/bin/clang-tidy" "/usr/local/bin/clang-tidy"
      - name: Download clang-tidy.py
        run: curl https://raw.githubusercontent.com/llvm-mirror/clang-tools-extra/master/clang-tidy/tool/run-clang-tidy.py -o run-clang-tidy.py
      - name: Configure CMake
        run: cmake $CMAKE_FLAGS -DCMAKE_BUILD_TYPE=$BUILD_TYPE .
      - name: Build
        run: cmake --build .
      - name: Run clang-tidy
        run: python3 run-clang-tidy.py
  #Linux
  clang-tidy-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/agarlicmonkey/clove/linux_analysis:2.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Download clang-tidy.py
        run: wget https://raw.githubusercontent.com/llvm-mirror/clang-tools-extra/master/clang-tidy/tool/run-clang-tidy.py
      - name: Configure CMake
        run: cmake $CMAKE_FLAGS -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -G "Unix Makefiles" .
      - name: Build
        run: cmake --build . 
      - name: Run clang-tidy
        run: python3 run-clang-tidy.py