name: Test
on:
  pull_request:
    branches: [master]
env:
  CMAKE_FLAGS: -DCLOVE_BUILD_TESTS=ON -DCLOVE_COMPILE_DEBUG_SHADERS=OFF -DCLOVE_ENABLE_AHA_VALIDATION=OFF -DCLOVE_ENABLE_ASSERTIONS=ON -DCLOVE_ENABLE_GHA_VALIDATION=OFF -DCLOVE_ENABLE_PROFILING=OFF -DCLOVE_MANUALLY_INSTALL_PACKAGES=ON -DCLOVE_USE_SAFE_CAST=ON
  BUILD_TYPE: Release
jobs:
  #Windows Jobs
  build-windows-msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup environment
      run: |
        mkdir build
        choco install -y conan
        curl.exe -o vksdk.exe https://sdk.lunarg.com/sdk/download/1.2.154.1/windows/VulkanSDK-1.2.154.1-Installer.exe?Human=true
        .\vksdk.exe /S /D=C:\VulkanSDK | Out-Null
    - name: Prime conan packages
      working-directory: ${{ github.workspace }}/build
      run: |
        $env:Path += ';C:\Program Files\Conan\conan'
        conan install .. --build=missing -s build_type=$env:BUILD_TYPE 
    - name: Configure CMake
      working-directory: ${{ github.workspace }}/build
      run: |
        $env:VULKAN_SDK = 'C:\VulkanSDK'
        $env:Path += ';C:\VulkanSDK\Bin;C:\Program Files\Conan\conan'
        #There seems to be an issue when using the env var of CMAKE_FLAGS on windows. When it has multiple options they're all treated as one
        cmake -DCLOVE_BUILD_TESTS=ON -DCLOVE_COMPILE_DEBUG_SHADERS=OFF -DCLOVE_ENABLE_AHA_VALIDATION=OFF -DCLOVE_ENABLE_ASSERTIONS=ON -DCLOVE_ENABLE_GHA_VALIDATION=OFF -DCLOVE_ENABLE_PROFILING=OFF -DCLOVE_MANUALLY_INSTALL_PACKAGES=ON -DCLOVE_USE_SAFE_CAST=ON -G "Visual Studio 16 2019" ..
    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: cmake --build . --target ALL_BUILD --config $env:BUILD_TYPE
    - name: Upload artefacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: windows-msvc
        path: build/
        retention-days: 1
  unit_test-windows-msvc:
    needs: [build-windows-msvc]
    runs-on: windows-latest
    steps:
      - name: Download build artefacts
        uses: actions/download-artifact@v2
        with:
          name: windows-msvc
          path: build/
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C $env:BUILD_TYPE
  #macOS Jobs
  build-macos-apple_clang:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup environment
        run: |
          mkdir build
          brew install conan
      - name: Prime conan packages
        working-directory: ${{ github.workspace }}/build
        run: conan install .. --build=missing -s build_type=$BUILD_TYPE
      - name: Configure CMake
        working-directory: ${{ github.workspace }}/build
        run: cmake $CMAKE_FLAGS -G "Xcode" ..
      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --target ALL_BUILD --config $BUILD_TYPE
      - name: Tar files to preserve permissions
        run: tar -cvf build_files.tar build/
      - name: Upload artefacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: macos-apple_clang
          path: build_files.tar
          retention-days: 1
  unit_test-macos-apple_clang:
    needs: [build-macos-apple_clang]
    runs-on: macos-latest
    steps:
      - name: Download build artefacts
        uses: actions/download-artifact@v2
        with:
          name: macos-apple_clang
          path: ./
      - name: Extract tar files
        run: tar -xvf build_files.tar
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C $BUILD_TYPE
  #Linux Jobs
  build-linux-gcc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/agarlicmonkey/clove/linux_build:1.2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup environment
        run: mkdir build
      - name: Prime conan packages
        working-directory: ${{ github.workspace }}/build
        run: conan install .. --build=missing -s build_type=$BUILD_TYPE -s compiler='gcc' -s compiler.version=10 -s compiler.libcxx=libstdc++11
      - name: Configure CMake
        working-directory: ${{ github.workspace }}/build
        run: cmake $CMAKE_FLAGS -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -G "Unix Makefiles" ..
      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build .
      - name: Tar files to preserve permissions
        run: tar -cvf build_files.tar build/
      - name: Upload artefacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: linux-gcc
          path: build_files.tar
          retention-days: 1
  build-linux-clang:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/agarlicmonkey/clove/linux_build:1.2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup environment
        run: mkdir build
      - name: Prime conan packages
        working-directory: ${{ github.workspace }}/build
        run: conan install .. --build=missing -s build_type=$BUILD_TYPE -s compiler='clang' -s compiler.version=10 -e CC=clang-10 -e CXX=clang++-10
      - name: Configure CMake
        working-directory: ${{ github.workspace }}/build
        run: cmake $CMAKE_FLAGS -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10 -G "Unix Makefiles" ..
      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build .
      - name: Tar files to preserve permissions
        run: tar -cvf build_files.tar build/
      - name: Upload artefacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: linux-clang
          path: build_files.tar
          retention-days: 1
  unit_test-linux-gcc:
    needs: [build-linux-gcc]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/agarlicmonkey/clove/linux_build:1.2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download build artefacts
        uses: actions/download-artifact@v2
        with:
          name: linux-gcc
          path: ./
      - name: Extract tar files
        run: tar -xvf build_files.tar
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C $BUILD_TYPE
  unit_test-linux-clang:
    needs: [build-linux-clang]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/agarlicmonkey/clove/linux_build:1.2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download build artefacts
        uses: actions/download-artifact@v2
        with:
          name: linux-clang
          path: ./
      - name: Extract tar files
        run: tar -xvf build_files.tar
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C $BUILD_TYPE
        
